name: Turbo GHA Docker

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Turbo Cache
        uses: rharkor/caching-for-turbo@2b4b5b14a8d16b8556a58993a8ac331d56d8906d
        continue-on-error: true
        with:
          provider: github
          max-age: 3d
          max-size: 500mb
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: rawnly/merge-queue-demo:latest
